### PR TITLE
Update CI runner

### PR DESCRIPTION
**Pull request by maxammann**
Should maybe wait until pesto is updated

fails because of https://github.com/tlspuffin/tlspuffin/issues/204

### CODE REVIEW

**Comment by LCBH** [comment]
> Should maybe wait until pesto is updated
> 
> fails because of #204

What kind of update do you expect on pesto? (I can do it!)

**Comment by maxammann** [comment]
> > Should maybe wait until pesto is updated
> > fails because of #204
> 
> What kind of update do you expect on pesto? (I can do it if it is not 20->22!)

We should not update pesto from 20->22 :) But this PR can only merged after that.

**Comment by michaelmera** [comment]
The linux distro on that particular server changed since this PR was opened and I failed to reproduce #204.

@maxammann Is there anything else preventing this PR to land in main?

**Comment by maxammann** [comment]
If tests pass then we can go ahead. But maybe we should wait until the pesto server updates.

It is nice to have binary comparability between those.

In fact I think we really should wait for pesto...

cc @LCBH

**Comment by michaelmera** [comment]
> If tests pass then we can go ahead. But maybe we should wait until the pesto server updates.
> 
> It is nice to have binary comparability between those.
> 
> In fact I think we really should wait for pesto...
> 

@maxammann I asked around and the pesto server update has already been done some months ago. However, it's not running Ubuntu anymore but Debian, so I wouldn't rely on it for binary comparability.

I will rebase this PR on main and merge it if there are no other objection.

**Comment by maxammann** [comment]
> > If tests pass then we can go ahead. But maybe we should wait until the pesto server updates.
> > It is nice to have binary comparability between those.
> > In fact I think we really should wait for pesto...
> 
> @maxammann I asked around and the pesto server update has already been done some months ago. However, it's not running Ubuntu anymore but Debian, so I wouldn't rely on it for binary comparability.
> 
> I will rebase this PR on main and merge it if there are no other objection.

In this case it is fine! I think there is no way to use GH-hosted runners with debian.

Feel free to merge.

**Comment by michaelmera** [comment]
> But of course things are never that easy. CI checks fail, but only for wolfssl430. I will have a look... 😢

So it appears that `bindgen` is using `clang-sys` which always [prefer the highest version of libclang](https://github.com/KyleMayes/clang-sys/tree/v1.6.1?tab=readme-ov-file#versioned-dependencies) available on the system.

The github-hosted runner ubuntu-22.04 has libclang-13, libclang-14 and libclang-15 installed but the default clang version is 14. So bindgen tries to use libclang-15 with clang-14 and those are compatible enough that everything is building except wolfssl430.

I added a fix to force the consistent pair clang-14/libclang-14 in the CI setup action.

**Comment by maxammann** [comment]
Sounds good! Clang 14 is the one to go for now.

**Comment by maxammann** [comment]
Thanks for those insights!

**Comment by maxammann** [comment]
Definitely a new reason to switch to Nix in the future :)

**Pull request merged**
