### PR TITLE
Fix tlspuffin hanging/crashing while fuzzing wolfssl

### PR DESCRIPTION
**Pull request by aeyno**
3f5e3da1ee57627508d57c7c80bc18d46b9272cb introduced a regression causing tlspuffin to crash/hang when fuzzing WolfSSL (see the crash report below).

This was caused by the fact that WolfSSL was not compiled with `-fsanitize-coverage=trace-pc-guard` even if `sancov` was set.

Crash report from `tlspuffin.log` when WolfSSL is compiled without `-fsanitize-coverage=trace-pc-guard` :
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CRASH ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Received signal SIGABRT at 0x007f61ebd9a83c, fault address: 0x00000000000000
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ REGISTERS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
r8 : 0x000abce433be38, r9 : 0x000abce433be31, r10: 0x00000000000008, r11: 0x00000000000246,
r12: 0x007ffcf8224f00, r13: 0x00000000000006, r14: 0x00000000000001, r15: 0x0055e321a33188,
rdi: 0x0000000004575d, rsi: 0x0000000004575d, rbp: 0x007f61ecb77a00, rbx: 0x0000000004575d,
rdx: 0x00000000000006, rax: 0x00000000000000, rcx: 0x007f61ebd9a83c, rsp: 0x007ffcf8224d20,
rip: 0x007f61ebd9a83c, efl: 0x00000000000246,
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   0: libafl::bolts::minibsod::generate_minibsod
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/libafl-0.10.1/src/bolts/minibsod.rs:637:30
   1: libafl::executors::inprocess::unix_signal_handler::inproc_crash_handler
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/libafl-0.10.1/src/executors/inprocess.rs:847:25
   2: libafl::executors::inprocess::unix_signal_handler::<impl libafl::bolts::os::unix_signals::Handler for libafl::executors::inprocess::InProcessExecutorHandlerData>::handle
   3: libafl::bolts::os::unix_signals::handle_signal
             at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/libafl-0.10.1/src/bolts/os/unix_signals.rs:376:5
   4: <unknown>
   5: <unknown>
   6: gsignal
   7: abort
   8: panic_abort::__rust_start_panic::abort
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/panic_abort/src/lib.rs:42:17
   9: __rust_start_panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/panic_abort/src/lib.rs:37:5
  10: rust_panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:740:9
  11: std::panicking::rust_panic_with_hook
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:710:5
  12: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  13: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  14: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  15: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  16: puffin::cli::main
  17: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
  18: main
  19: <unknown>
  20: __libc_start_main
  21: _start
```

### CODE REVIEW

**Comment by aeyno** [comment]
Looks like the tests are failing because of the certificate verifications. Is it related to #281 ?

**Comment by maxammann** [comment]
Yes! I merged that other PR and reran the builds here.

**Comment by maxammann** [comment]
Rerunning builds

**Comment by LCBH** [comment]
Will merge this.

**Pull request merged**
