### PR TITLE
Add support for OpenSSL 3

### PR DESCRIPTION
**Pull request by maxammann**

### CODE REVIEW

**Comment by LCBH** [comment]
@maxammann Do you want to update and merge?

**Comment by maxammann** [comment]
Yes, I'll review this again and then merge! :)

**Comment by maxammann** [comment]
Hm, not sure why these builds are failing

**Review by michaelmera — COMMENTED** [review]
I think this is the change that breaks part of the CI: before OpenSSL 1.1.1 the libdir argument is always relative to the prefix.

What was the reason for adding this change?

see also upstream:
- issue: https://github.com/openssl/openssl/issues/5398
- fixed by: https://github.com/openssl/openssl/commit/e454f3add638fda5c2aa32cd368c8929c0b1eb09

**Pull request merged**
